export const dummyPosts = [
  {
    id: 1,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 2,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 3,
    status: '모집완료',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 4,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 5,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 6,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모잡글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 7,
    status: '모집완료',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 8,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 9,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
  {
    id: 10,
    status: '모집중',
    date: '25.01.01~25.01.01',
    title: '동행모집글 타이틀',
    description: '두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개두줄소개',
    imageUrl: '/assets/icons/logoWithHappy.png',
    tags: ['20대', '여성', '주말'],
  },
]
