import './globals.css'
import localFont from 'next/font/local'
import type { Metadata } from 'next'
import { cn } from '@/utils/cn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendardFont = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(pretendardFont.className, 'mx-auto h-[100dvh] w-[360px] border-r border-l')}
      >
        {children}
      </body>
    </html>
  )
}
