import './globals.css';
import localFont from 'next/font/local';
import type { Metadata } from 'next';
import BodyWrapper from '@/components/layout/BodyWrapper';

const pretendardFont = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendardFont.className} mx-auto min-h-[100dvh] w-[360px] border-l border-r pb-[65px]`}
      >
        <BodyWrapper>{children}</BodyWrapper>
      </body>
    </html>
  );
}
